# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/node:10.16.3
#     working_directory: ~/repo
#     steps:
#       - checkout
#       # install dependencies
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Build
#           command: npm run build

# workflows:
#   jobs:
#     - build

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:12.9.1-browsers

#     working_directory: ~/repo
#     steps:
#       - checkout

#       - restore_cache:
#       keys:
#         - v1-dependencies-{{ checksum "package.json" }}
#       - v1-dependencies-

#   - run: yarn install

#   - save_cache:
#     paths:
#       - node_modules
#       - ~/.npm
#       - ~/.cache
#     key: v1-dependencies-{{ checksum "package.json" }}

#   - run: yarn test
version: 2.1
# jobs is the task which are working for

jobs:
  test:
    docker:
      - image: cimg/node:18.7.0
    working_directory: ~/my-app/

    steps:
      - checkout
      - run:
          name: lsist
          command: ls my-app/

      - run:
          name: pwd
          command: pwd
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test

workflows:
  test-depoly:
    jobs:
      - test
      # - two
