version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/my-app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "my-app/package.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run:
          name: install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "my-app/package.json" }}

      # run tests!
      - run:
          command: cd my-app && npm test

      # - run: yarn build

      # - run: yarn netlify:deploy
