version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

workflows:
  heroku_deploy:
    jobs:
      - build
